# Generated by Django 5.1.7 on 2025-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='videos/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(max_length=256)),
            ],
        ),
    ]
