# Generated by Django 5.1.7 on 2025-09-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
