# Generated by Django 5.1.7 on 2025-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='token', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
