# Generated by Django 5.1.7 on 2025-07-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoflixuser',
            name='date_of_birth',
        ),
    ]
