# Generated by Django 5.1.7 on 2025-08-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_sendverifymail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendVerifyMail',
        ),
    ]
